### ISSUE TITLE
Can you improve your readme content

### ISSUE THREAD

**Issue by mooncakehub** [wu-zhonghua/RAC-Net#1]
Thank you for your great work,  Can you describe in detail how to configure the environment and start training?

**Comment by wu-zhonghua** [comment]
Thanks for your interesting in our work. We will update the codes after the acceptance of this paper. Thanks.

**Comment by mooncakehub** [comment]
Thank you for your reply.And I hope your code can be trained with multi-GPUs,Because my single gpu memory is not enough.Thank you very much

**Comment by Yellowshuohahaha** [comment]
@wu-zhonghua Congratulations on your paper being accepted by IJCV! I wonder what the pointnet2 directory in the code is used for? And the code about the part of point transformer can be released?

**Comment by wu-zhonghua** [comment]
We have released the code with the Point Transformer backbone. Feel free to ask me if you have further questions.

**Comment by Yellowshuohahaha** [comment]
@wu-zhonghua Thanks for your excellent work!

**Comment by Yellowshuohahaha** [comment]
@wu-zhonghua Hi, when I run the code, It shows that forward of memory, and the value of lds_wolf and lds_cda will both be 0. Is this normal, or is my gpu running out of memory?
![image](https://github.com/wu-zhonghua/RAC-Net/assets/48409315/3fa7af7a-1407-4190-a4eb-0621ddf57307)

**Comment by wu-zhonghua** [comment]
Yes, your GPU running out of memory. It is better if you could use more powerful gpu or reduce the batch size.

**Comment by Wjy0316** [comment]
> @wu-zhonghua Hi, when I run the code, It shows that forward of memory, and the value of lds_wolf and lds_cda will both be 0. Is this normal, or is my gpu running out of memory? ![image](https://private-user-images.githubusercontent.com/48409315/301787892-3fa7af7a-1407-4190-a4eb-0621ddf57307.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MjY5MzcsIm5iZiI6MTcyMjkyNjYzNywicGF0aCI6Ii80ODQwOTMxNS8zMDE3ODc4OTItM2ZhN2FmN2EtMTQwNy00MTkwLWE0ZWItMDYyMWRkZjU3MzA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA2NDM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4ZTVkNjc4ZGUyMWY5MGRjYjM5MWZhNDQ5Yzc1YzRiNGRmZWZlZjFmYWE2MDExOTY1Nzk3ZWU5YTcwZTE2ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VnUGMpe9oOWbiGGDBIIeJP88eZtOKgi4_yYt2EY4AhM)



> @wu-zhonghua Hi, when I run the code, It shows that forward of memory, and the value of lds_wolf and lds_cda will both be 0. Is this normal, or is my gpu running out of memory? ![image](https://private-user-images.githubusercontent.com/48409315/301787892-3fa7af7a-1407-4190-a4eb-0621ddf57307.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5OTI0OTMsIm5iZiI6MTcyMjk5MjE5MywicGF0aCI6Ii80ODQwOTMxNS8zMDE3ODc4OTItM2ZhN2FmN2EtMTQwNy00MTkwLWE0ZWItMDYyMWRkZjU3MzA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDAwNTYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3YmViN2MxY2E1NzM2ZTk1ZmUyN2MxYTQ5Yzc5MDQ0YjA3ZjZkOTA0ZGVhYjcwMTUzZWYwM2Q2NTVkMmMyODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nAoHvYRWB2YEuxIp2kaREj4oUyEk-G_abYlvr27fhC8)

I had the same problem as you and was wondering how you ended up solving it? I used two 3090 GPUs running together and set the batch size to 2, and I still get this problem.

**Comment by Wjy0316** [comment]
> @wu-zhonghua Hi, when I run the code, It shows that forward of memory, and the value of lds_wolf and lds_cda will both be 0. Is this normal, or is my gpu running out of memory? ![image](https://private-user-images.githubusercontent.com/48409315/301787892-3fa7af7a-1407-4190-a4eb-0621ddf57307.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5OTI5NzMsIm5iZiI6MTcyMjk5MjY3MywicGF0aCI6Ii80ODQwOTMxNS8zMDE3ODc4OTItM2ZhN2FmN2EtMTQwNy00MTkwLWE0ZWItMDYyMWRkZjU3MzA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDAxMDQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MDg2Yjg3Y2M5MmYwYjFiMzNlMDA0YjBhN2YyNzk2MzFkNzg2NGI3NzU3N2FhOTkyNTQ4NWFkMzUxOGE0ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d3j7QdGI6bZQLIyHLg378Qrs94Qvr_lWNsdYa8LE64E)

@Yellowshuohahaha I had the same problem as you and was wondering how you ended up solving it? I used two 3090 GPUs running together and set the batch size to 2, and I still get this problem.

**Comment by Spring121212** [comment]
您好，非常感谢您的工作！我在文章中看到您用的是单个3090跑通的，我们用相同的配置也会出现内存不足的情况，这是为什么呢？
